# Generated by Django 4.0.3 on 2022-05-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobs_arquivo_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='categoria',
            field=models.CharField(choices=[('D', 'Design'), ('EV', 'Edição de Vídeo'), ('FS', 'Full-Stack'), ('BE', 'Back-End'), ('FE', 'Front-End')], default='D', max_length=2),
        ),
    ]
